name: Daily Release

on:
  schedule:
    - cron: '59 12 * * *'

jobs:
  Tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/daily-version-action@v1
        id: daily-version
        with:
          prefix: v
